services:
  - type: web
    name: ocr-api
    runtime: docker
    region: singapore
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    buildFilter:
      paths: ["Dockerfile", "requirements.txt", "**/*.py"]
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
